### PR TITLE
Proton

### PR DESCRIPTION
**Pull request by NL-TCH**
Add gaming section + Proton compatibility layer to prevent maintaining multiple Winepreloaders and Wineservers

### CODE REVIEW

**Comment by NL-TCH** [comment]
this matches all steam provided proton versions + custom GE versions in the compatibilitytools.d folder

**Comment by NL-TCH** [comment]
is this also the right place to add outgoing rules?
like `prod-telemetry.paradox-interactive.com` ? (telemetry)

**Comment by Raphty** [comment]
Regarding the "completeness" of those profiles, I think this is an etiquette  that can form over time... you can merge multiple profiles, but the settings in the later profile will override the ones in the already applied one... also rules don't merge but will be overwritten.

I think starting with complete profiles and not having to apply multiple ones is a good thing

but there will always be a need for generic ones with little rules in them.

**Comment by NL-TCH** [comment]
see new rebased pullrequest

**Pull request closed without merging**
