### PR TITLE
Ausweis App

### PR DESCRIPTION
**Pull request by Max-F-Helm**
Profiles for the German AusweisApp (installed via Flatpak).

### CODE REVIEW

**Comment by Raphty** [comment]
thanks for the contribution, if I may ask, why is this two apps?

also I saw that you allow Incoming connections in one but block internet.

we recommend allowing what you want and blocking the rest

```
type: profile
id: PTM3U2aYeA1P4DhEq56mVDwrvLm2id27jTTR47UeA35sGW
source: local
name: Ausweis App
presPath: /app/bin/AusweisApp
usePresPath: true
fingerprints:
    - type: path
      operation: equals
      value: /app/bin/AusweisApp
config:
    filter:
        blockInbound: false
        serviceEndpoints:
            - + LAN
            - + Localhost
            - '- *'
lastEdited: 2023-12-13T13:31:41+01:00
created: 2023-11-07T09:18:15+01:00

# jess-checksum: Zwkj7zETAtAjiJT5CPdua8FZZKwtaN4Xohbu2M2whbd9nb
```

**Comment by Raphty** [comment]
image

**Comment by Max-F-Helm** [comment]
@Raphty 

> why is this two apps?

I also don't know. I installed AusweisApp via Flatpak and that is what is in the installation.

> we recommend allowing what you want and blocking the rest

Thanks for the recommendation.
I will test if this works and will update the PR accordingly.

**Comment by Max-F-Helm** [comment]
The rules are working, so I updated the PR.

Should I remove the IDs here too?

**Comment by Raphty** [comment]
no that ID is (for some reason) the new one... we are looking into why some Portmasters appeared to not have updated the IDs

I did just change the structure of the repo so that all apps get their own folders... I can do the move, or you can do it.

the idea would be in your case that you can also have both profiles in one folder and explaining in a  readme what this app is. I just copied for instance text from the home page.

in this case:

README.txt

```
# Ausweis App [ger]

Mit der Online-Ausweisfunktion Ihres Personalausweises, elektronischen Aufenthaltstitels oder Ihrer eID-Karte können Sie sich online eindeutig und sicher identifizieren.

https://www.ausweisapp.bund.de/home/

```

**Comment by Max-F-Helm** [comment]
Updated the PR to match the new directory layout.

I also removed the profile of AusweisApp2 as it seems that this was for an older installation of this software.

**Review by NL-TCH — CHANGES_REQUESTED** [review]
Thanks for the contribution!
A few comments:
1. Even though this is a German app, please create the AusweisApp/README.md also in english. You can just add a section with "Ausweis App [en]"
2. thanks for fixing the kdeconnect link, but please create a separate PR for this

**Review by NL-TCH — APPROVED** [review]

**Comment by Max-F-Helm** [comment]
(when you merge this, I would prefer if squash the commits)

**Comment by dhaavi** [comment]
If this profile is for the flatpak, it would great to match the flatpak ID. This will make sure it will also match anything else inside the flatpak and will survive changes within the flatpak.

You can find this stuff when you open the process details on a connection. There will be a section called "Tags" where you can also easily create a new profile with the selected tag.

**Comment by Max-F-Helm** [comment]
> If this profile is for the flatpak, it would great to match the flatpak ID. This will make sure it will also match anything else inside the flatpak and will survive changes within the flatpak.
> 
> You can find this stuff when you open the process details on a connection. There will be a section called "Tags" where you can also easily create a new profile with the selected tag.

It is a Flatpak.

But unfortunately I am unable to locate the section with 'Tags'.
The only thing I found was 'Fingerprints', but this lists only the path, which is already in the exported profile ('/app/bin/AusweisApp').

**Comment by dhaavi** [comment]
Do you know if it is based on electron?

**Comment by Max-F-Helm** [comment]
According to the GitHub Repo, it is written with Qt

**Comment by dhaavi** [comment]
Okay.

Then if you open any connection of the app and press "Process Details":
image

You should see the flatpak tag as here:
image

I just realized we don't have the cool "plus" button to create a profile there yet, but this will come soon.

**Comment by Max-F-Helm** [comment]
Ok, I found it. Thank you.

The `flatpak-id` is `de.bund.ausweisapp.ausweisapp2`

How do I have to adjust the yml?

**Comment by dhaavi** [comment]
Yes, you can either do that - the yml would look like this:

```
fingerprints:
    - type: tag
      key: flatpak-id
      operation: equals
      value: de.bund.ausweisapp.ausweisapp2
```

Or, you can export your settings and delete the app in Portmaster. It will be recreated as soon as there is a connection (immediately if Portmaster already has one.) with the flatpak fingerprint.

**Comment by Max-F-Helm** [comment]
PR updated with recreated profile.

**Review by dhaavi — APPROVED** [review]

**Review by NL-TCH — APPROVED** [review]

**Comment by NL-TCH** [comment]
squashed and merged

**Pull request merged**
