### PR TITLE
fix spelling mistake in KDE Connect README.md

### PR DESCRIPTION
**Pull request by Max-F-Helm**

### CODE REVIEW

**Review by NL-TCH — APPROVED** [review]

**Review by Raphty — APPROVED** [review]

**Review by NL-TCH — APPROVED** [review]

**Comment by dhaavi** [comment]
Hey @NL-TCH, Raphael asked to look into the approval process here.
It seems you have requested a review from yourself, so we are back to one review.
You should be able to approve the PR and then merge it yourself.

**Review by NL-TCH — APPROVED** [review]

**Comment by NL-TCH** [comment]
thanks for the message Daniel,
i approved the PR again, but still one official approval

image

**Comment by dhaavi** [comment]
Ok, I think I understand. It should work now, please try again.

**Comment by NL-TCH** [comment]
yes, there are now 2 reviewers, so now i can merge. thanks
and sorry for cluttering up this PR :)

**Pull request merged**
